services:
  web-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: web-frontend
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:82
      - VITE_AUTH_URL=http://localhost:82
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - dlmobile_deuceleague

networks:
  dlmobile_deuceleague:
    external: true
    name: dlmobile_deuceleague
